version: "4.19"
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2288:3288;zookeeper-2:3288:33888;zookeeper-3:4288:4388
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
      ZOOKEEPER_LOG4J_LOGLEVEL: ERROR    
    ports:
      - 2181:2181
  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 3181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2288:3288;zookeeper-2:3288:33888;zookeeper-3:4288:4388
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
      ZOOKEEPER_LOG4J_LOGLEVEL: ERROR
    ports:
      - 3181:3281
  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 4181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2288:3288;zookeeper-2:3288:33888;zookeeper-3:4288:4388
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
      ZOOKEEPER_LOG4J_LOGLEVEL: ERROR    
    ports:
      - 4181:4181
  kafka1:
   image: confluentinc/cp-kafka:latest
   ports:
      - "9092:9092"
   depends_on:
     -  zookeeper-1
     -  zookeeper-2
     -  zookeeper-3
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:3181,zookeeper-3:4181
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9093,PLAINTEXT_HOST://localhost:9092
     KAFKA_LISTENERS: PLAINTEXT://:9093,PLAINTEXT_HOST://:9092
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
     KAFKA_NUM_PARTITIONS: 3
     KAFKA_OPTS: -Djute.maxbuffer=500000000
     KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
     KAFKA_LOG4J_LOGLEVEL: ERROR
   healthcheck:
     test: kafka-topics --bootstrap-server kafka1:9093 --list
     interval: 30s
     timeout: 10s
     retries: 10
  kafka2:
   image: confluentinc/cp-kafka:latest
   ports:
      - "9094:9094"
   depends_on:
     -  zookeeper-1
     -  zookeeper-2
     -  zookeeper-3
   environment:
     KAFKA_BROKER_ID: 2
     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:3181,zookeeper-3:4181
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9095,PLAINTEXT_HOST://localhost:9094
     KAFKA_LISTENERS: PLAINTEXT://:9095,PLAINTEXT_HOST://:9094
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
     KAFKA_NUM_PARTITIONS: 3
     KAFKA_OPTS: -Djute.maxbuffer=500000000
     KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
     KAFKA_LOG4J_LOGLEVEL: ERROR
   healthcheck:
     test: kafka-topics --bootstrap-server kafka2:9095 --list
     interval: 30s
     timeout: 10s
     retries: 10
  kafka3:
   image: confluentinc/cp-kafka:latest
   ports:
      - "9096:9096"
   depends_on:
     -  zookeeper-1
     -  zookeeper-2
     -  zookeeper-3
   environment:
     KAFKA_BROKER_ID: 3
     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:3181,zookeeper-3:4181
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9097,PLAINTEXT_HOST://localhost:9096
     KAFKA_LISTENERS: PLAINTEXT://:9097,PLAINTEXT_HOST://:9096
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
     KAFKA_NUM_PARTITIONS: 3
     KAFKA_OPTS: -Djute.maxbuffer=500000000
     KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
     KAFKA_LOG4J_LOGLEVEL: ERROR
   healthcheck:
     test: kafka-topics --bootstrap-server kafka3:9097 --list
     interval: 30s
     timeout: 10s
     retries: 10
  producer:
    build:
      context: producer
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
  preprocessor:
    build:
      context: preprocessor
      dockerfile: Dockerfile
    container_name: preprocessor
    ports:
      - "4040:4040"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040"]
      interval: 30s
      timeout: 10s
      retries: 10
  consumer:
    build:
      context: consumer
      dockerfile: Dockerfile
    container_name: consumer
    ports:
      - "5006:5006"
    environment:
      - SLEEP_CONSUMPTION=0.1
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      preprocessor:
        condition: service_healthy
  # for monitoring we use kafdrop on http://localhost:9000
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka1:9093,kafka2:9095,kafka3:9097
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy